/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_bingbindong_myapplication_utils_jniTest */

#ifndef _Included_com_example_bingbindong_myapplication_utils_jniTest
#define _Included_com_example_bingbindong_myapplication_utils_jniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_bingbindong_myapplication_utils_jniTest
 * Method:    changeFloatFromCpp
 * Signature: ([FI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_example_bingbindong_myapplication_utils_jniTest_changeFloatFromCpp
  (JNIEnv *, jobject, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
